name: Lerna Publish

on:
  pull_request:
    branches: [feature/*]
    types: [opened, reopened, synchronize]

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn lerna version preminor --preid rc
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      # - uses: actions/setup-node@v1
      #   with:
      #     registry-url: 'https://npm.pkg.github.com'
      # - run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
