name: Lerna Publish

on:
  pull_request:
    types: [opened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn lerna version preminor --preid rc
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      # - uses: actions/setup-node@v1
      #   with:
      #     registry-url: 'https://npm.pkg.github.com'
      # - run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
