name: Lerna Publish

on:
  pull_request:
    # branches:
    # - feature/**
    types: [opened, reopened, synchronize]

jobs:
  publish_feat:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Configure CI Git User
        run: |
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "registry=https://registry.npmjs.org/:_authToken=$YARN_TOKEN" > ~/.npmrc
          npm whoami
        env:
          YARN_TOKEN: ${{ secrets.YARN_TOKEN }}

      - run: yarn install
      - run: yarn lerna publish prerelease --yes --preid feat --force-publish --skip-git
