name: Lerna Publish

on:
  pull_request:
    # branches:
    # - feature/**
    types: [opened, reopened, synchronize]

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn lerna publish prerelease --yes --preid feat --force-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
# - uses: actions/setup-node@v1
#   with:
#     registry-url: 'https://npm.pkg.github.com'
# - run: yarn publish
#   env:
#     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
